### ISSUE TITLE
Description shall be in English. 

### ISSUE THREAD

**Issue by mpostol** [asasinowski/TPUM#2]
Consider using English in public repositories - people are looking 🤕.

**Comment by asasinowski** [comment]
Done.

**Comment by mpostol** [comment]
![Capture](https://user-images.githubusercontent.com/11937915/77737848-0fcaf100-700f-11ea-8241-10f1e87d6524.PNG)

Use labels like `invalid` or `wontfix` to communicate your decision If you don't agree on.

**Comment by asasinowski** [comment]
Forgot to save changes, this time it is done for sure
